# Generated by Django 5.0.4 on 2024-05-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="description",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
